In [1]:
import numpy as np
import cv2
import face_recognition
import os
from datetime import datetime
from timeit import default_timer as timer
from imutils import paths

tempNames and myList

In [4]:
imagePaths = list(paths.list_images('dataset-1'))
tempNames = []

for (i, imagePath) in enumerate(imagePaths):
    name = imagePath.split(os.path.sep)[-1]
    tempNames.append(name)
    
tempNames

['billgates_01.jpg',
 'billgates_02.jpeg',
 'drphil_01.jpg',
 'elonmusk_01.jpg',
 'jackma_01.jpg']

In [6]:
path = 'dataset-1'
myList = os.listdir(path)
myList

['billgates_01.jpg',
 'billgates_02.jpeg',
 'drphil_01.jpg',
 'elonmusk_01.jpg',
 'jackma_01.jpg']

classNames and knownNames

In [8]:
images = []
classNames = []

for cl in myList:
    curImg = cv2.imread(f'{path}/{cl}')
    images.append(curImg)
    classNames.append(os.path.splitext(cl)[0])
classNames

['billgates_01', 'billgates_02', 'drphil_01', 'elonmusk_01', 'jackma_01']

In [17]:
knownEncodings = []
knownNames = []
images = []
path = 'dataset-1'
myList = os.listdir(path)

In [18]:
myList

['billgates_01.jpg',
 'billgates_02.jpeg',
 'drphil_01.jpg',
 'elonmusk_01.jpg',
 'jackma_01.jpg']

In [54]:
knownNames = []
knownEncodings = []
images = []

In [57]:
start = timer()
imagePaths = list(paths.list_images('dataset-1'))
tempNames = []

def findEncodings(images):
    encodeList = []
    for img in images:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        encode = face_recognition.face_encodings(img)[0]
        encodeList.append(encode)
    return encodeList  

for (i, imagePath) in enumerate(imagePaths):
    name = imagePath.split(os.path.sep)[-1]
    tempNames.append(name)

for x in filter(lambda w: w not in knownNames, tempNames):
    print('Processing...')
    x = cv2.imread(imagePath)
    images.append(x)

    knownEncodings = findEncodings(images)
    

#     for rgb in images:
#         rgb = cv2.cvtColor(rgb, cv2.COLOR_BGR2RGB)
# #     boxes = face_recognition.face_locations(rgb, model='hog')
#         encodings = face_recognition.face_encodings(rgb)[0]
#         knownEncodings.append(encodings)
    
#     for encoding in encodings:
#         knownEncodings.append(encoding)
#         knownNames.append(x)

knownNames = list(dict.fromkeys(tempNames))

print(f'Time: {timer()-start}')
print(knownNames)
print(len(knownEncodings))

Time: 0.0016571000001022185
['billgates_01.jpg', 'billgates_02.jpeg', 'drphil_01.jpg', 'elonmusk_01.jpg', 'jackma_01.jpg']
5


**big difference**: images

In [58]:
images

[array([[[ 74,  68,  39],
         [ 74,  68,  39],
         [ 74,  68,  39],
         ...,
         [ 87,  85,  27],
         [ 87,  85,  27],
         [ 87,  86,  26]],
 
        [[ 74,  68,  39],
         [ 74,  68,  39],
         [ 74,  68,  39],
         ...,
         [ 87,  85,  27],
         [ 87,  85,  27],
         [ 87,  85,  27]],
 
        [[ 74,  68,  39],
         [ 74,  68,  39],
         [ 74,  68,  39],
         ...,
         [ 87,  85,  27],
         [ 87,  85,  27],
         [ 87,  85,  27]],
 
        ...,
 
        [[ 90,  96,  41],
         [ 92,  99,  42],
         [ 94, 102,  42],
         ...,
         [ 88,  98,  28],
         [ 88,  98,  28],
         [ 88,  98,  28]],
 
        [[ 84,  90,  35],
         [ 86,  92,  37],
         [ 88,  96,  36],
         ...,
         [ 88,  98,  28],
         [ 88,  98,  28],
         [ 88,  98,  28]],
 
        [[ 86,  92,  39],
         [ 88,  94,  39],
         [ 89,  96,  39],
         ...,
         [ 88,  98,  28],
  

In [13]:
len(images)

5

In [22]:
imagePaths

['dataset-1\\billgates_01.jpg',
 'dataset-1\\billgates_02.jpeg',
 'dataset-1\\drphil_01.jpg',
 'dataset-1\\elonmusk_01.jpg',
 'dataset-1\\jackma_01.jpg']

In [23]:
tempNames

['billgates_01.jpg',
 'billgates_02.jpeg',
 'drphil_01.jpg',
 'elonmusk_01.jpg',
 'jackma_01.jpg']

In [24]:
myList

['billgates_01.jpg',
 'billgates_02.jpeg',
 'drphil_01.jpg',
 'elonmusk_01.jpg',
 'jackma_01.jpg']

In [26]:
imagePath

'dataset-1\\jackma_01.jpg'

In [27]:
for (i, imagePath) in enumerate(imagePaths):
    print(imagePath)

dataset-1\billgates_01.jpg
dataset-1\billgates_02.jpeg
dataset-1\drphil_01.jpg
dataset-1\elonmusk_01.jpg
dataset-1\jackma_01.jpg


In [34]:
tempNames

['billgates_01.jpg',
 'billgates_02.jpeg',
 'drphil_01.jpg',
 'elonmusk_01.jpg',
 'jackma_01.jpg']

In [47]:
knownEncodings

[array([-0.08246521,  0.04031427, -0.01992257, -0.0759159 , -0.04292411,
        -0.13713919,  0.00201854, -0.15142697,  0.09080262, -0.0652807 ,
         0.18045434, -0.00524626, -0.14689216, -0.10947868,  0.04229798,
         0.14507961, -0.20682275, -0.21029899, -0.09510187, -0.02723093,
         0.08055536, -0.0751159 ,  0.02351749,  0.00849729, -0.05648863,
        -0.26348615, -0.14219354, -0.05341547,  0.10467769,  0.04729266,
         0.06047993,  0.03309834, -0.23036535, -0.1119489 ,  0.08591321,
         0.08289906, -0.02210294, -0.08757359,  0.2226059 , -0.01987426,
        -0.19136102,  0.05862528,  0.04014895,  0.24178353,  0.16554843,
         0.01289478,  0.07804212, -0.12399038,  0.06012492, -0.15900351,
         0.06779163,  0.12386309,  0.1224832 ,  0.09838496, -0.01362169,
        -0.15356006,  0.14416169,  0.08953121, -0.21129006, -0.03369501,
         0.10853923, -0.06519959, -0.02839306, -0.01103735,  0.21356738,
         0.10201447, -0.05080377, -0.23387599,  0.1

In [49]:
len(images)

5

In [50]:
images

[array([[[ 74,  68,  39],
         [ 74,  68,  39],
         [ 74,  68,  39],
         ...,
         [ 87,  85,  27],
         [ 87,  85,  27],
         [ 87,  86,  26]],
 
        [[ 74,  68,  39],
         [ 74,  68,  39],
         [ 74,  68,  39],
         ...,
         [ 87,  85,  27],
         [ 87,  85,  27],
         [ 87,  85,  27]],
 
        [[ 74,  68,  39],
         [ 74,  68,  39],
         [ 74,  68,  39],
         ...,
         [ 87,  85,  27],
         [ 87,  85,  27],
         [ 87,  85,  27]],
 
        ...,
 
        [[ 90,  96,  41],
         [ 92,  99,  42],
         [ 94, 102,  42],
         ...,
         [ 88,  98,  28],
         [ 88,  98,  28],
         [ 88,  98,  28]],
 
        [[ 84,  90,  35],
         [ 86,  92,  37],
         [ 88,  96,  36],
         ...,
         [ 88,  98,  28],
         [ 88,  98,  28],
         [ 88,  98,  28]],
 
        [[ 86,  92,  39],
         [ 88,  94,  39],
         [ 89,  96,  39],
         ...,
         [ 88,  98,  28],
  

In [53]:
for x in filter(lambda w: w not in knownNames, tempNames):
    print(x)

billgates_01.jpg
billgates_02.jpeg
drphil_01.jpg
elonmusk_01.jpg
jackma_01.jpg


In [63]:
knownNames = []
knownEncodings = []
images = []
path = 'dataset-1'

In [64]:
imagePaths = list(paths.list_images('dataset-1'))
tempNames = []
for (i, imagePath) in enumerate(imagePaths):
    name = imagePath.split(os.path.sep)[-1]
    tempNames.append(name)

for x in filter(lambda w: w not in knownNames, tempNames):
    print('Processing...')
    img = cv2.imread(f'{path}/{x}')
    print(img)

Processing...
[[[143 124 116]
  [143 124 116]
  [143 124 116]
  ...
  [167 152 149]
  [168 153 150]
  [168 153 150]]

 [[143 124 116]
  [143 124 116]
  [143 124 116]
  ...
  [167 152 149]
  [168 153 150]
  [168 153 150]]

 [[143 124 116]
  [143 124 116]
  [144 125 117]
  ...
  [167 152 149]
  [168 153 150]
  [168 153 150]]

 ...

 [[179 132 148]
  [181 134 150]
  [182 135 151]
  ...
  [129 120 116]
  [129 120 116]
  [129 120 116]]

 [[178 131 147]
  [180 133 149]
  [182 135 151]
  ...
  [129 120 116]
  [129 120 116]
  [129 120 116]]

 [[179 132 148]
  [180 133 149]
  [182 135 151]
  ...
  [129 120 116]
  [129 120 116]
  [129 120 116]]]
Processing...
[[[190 201 205]
  [190 201 205]
  [190 201 205]
  ...
  [179 167 161]
  [182 169 161]
  [182 169 161]]

 [[190 201 205]
  [190 201 205]
  [190 201 205]
  ...
  [180 168 162]
  [182 169 161]
  [182 169 161]]

 [[189 200 204]
  [190 201 205]
  [190 201 205]
  ...
  [183 169 163]
  [182 168 162]
  [182 168 162]]

 ...

 [[178 195 192]
  [178 1

In [113]:
knownNames = []
knownEncodings = []
images = []
path = 'dataset-1'

In [114]:
start = timer()
imagePaths = list(paths.list_images('dataset-1'))
tempNames = []

def findEncodings(images):
    for img in images:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        encode = face_recognition.face_encodings(img)
        knownEncodings.append(encode)
    return knownEncodings  

# def findEncodings2(images):
#     encodeList = []
#     for img in images:
#         img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
#         encode = face_recognition.face_encodings(img)[0]
#         encodeList.append(encode)
#     return encodeList

for (i, imagePath) in enumerate(imagePaths):
    name = imagePath.split(os.path.sep)[-1]
    tempNames.append(name)

for x in filter(lambda w: w not in knownNames, tempNames):
    print('Processing...')
    img = cv2.imread(f'{path}/{x}')
    images.append(img)

    findEncodings(images)
    

#     for rgb in images:
#         rgb = cv2.cvtColor(rgb, cv2.COLOR_BGR2RGB)
# #     boxes = face_recognition.face_locations(rgb, model='hog')
#         encodings = face_recognition.face_encodings(rgb)[0]
#         knownEncodings.append(encodings)
    
#     for encoding in encodings:
#         knownEncodings.append(encoding)
#         knownNames.append(x)

knownNames = list(dict.fromkeys(tempNames))
# knownEncodings = list(dict.fromkeys(knownEncodings))

print(f'Time: {timer()-start}')
print(knownNames)
print(len(knownEncodings))

Processing...
Processing...
Processing...
Processing...
Processing...
Time: 14.228071999999884
['billgates_01.jpg', 'billgates_02.jpeg', 'drphil_01.jpg', 'elonmusk_01.jpg', 'jackma_01.jpg']
15


In [107]:
knownEncodings

[[array([-7.78014883e-02,  1.00938603e-01,  1.27612893e-02, -1.54165216e-02,
         -1.74832687e-01, -2.33827960e-02, -7.97428042e-02, -1.49676085e-01,
          1.29436016e-01, -7.45923519e-02,  1.47503763e-01,  7.45223835e-03,
         -1.82138771e-01, -2.75230734e-03, -2.29673870e-02,  6.47304282e-02,
         -2.07118005e-01, -1.04713984e-01, -1.19404875e-01, -1.09362751e-01,
         -5.86776398e-02,  1.98414549e-02,  1.93376057e-02, -2.56121159e-04,
         -1.33486509e-01, -1.98222682e-01, -1.38347447e-01, -1.39369115e-01,
          1.74305543e-01, -8.88103619e-02,  8.94454867e-03,  7.46188834e-02,
         -1.58124194e-01, -8.83737504e-02,  5.53894117e-02,  1.27452284e-01,
         -7.51968324e-02, -2.25475021e-02,  1.85055569e-01,  2.11284533e-02,
         -1.41231060e-01, -2.23658308e-02,  6.15880527e-02,  2.53549188e-01,
          2.68987596e-01,  8.67981687e-02,  5.98824956e-03, -4.37789746e-02,
          1.42188653e-01, -2.27694154e-01,  7.68692195e-02,  1.65807411e-01,

In [71]:
len(images)

5

In [83]:
list(set(knownEncodings))

TypeError: unhashable type: 'numpy.ndarray'

In [82]:
set((knownEncodings))

TypeError: unhashable type: 'numpy.ndarray'

In [85]:
listoflists = []
a_list = []
for i in range(0,10):
    a_list.append(i)
    if len(a_list)>3:
        a_list.remove(a_list[0])
        listoflists.append((list(a_list), a_list[0]))
print(listoflists)

[([1, 2, 3], 1), ([2, 3, 4], 2), ([3, 4, 5], 3), ([4, 5, 6], 4), ([5, 6, 7], 5), ([6, 7, 8], 6), ([7, 8, 9], 7)]


In [87]:
list(dict.fromkeys(knownEncodings))

TypeError: unhashable type: 'numpy.ndarray'

In [88]:
l = [(2,2),(2,3),(1,4),(2,2)]
l

[(2, 2), (2, 3), (1, 4), (2, 2)]

In [89]:
knownEncodings

[array([-7.78014883e-02,  1.00938603e-01,  1.27612893e-02, -1.54165216e-02,
        -1.74832687e-01, -2.33827960e-02, -7.97428042e-02, -1.49676085e-01,
         1.29436016e-01, -7.45923519e-02,  1.47503763e-01,  7.45223835e-03,
        -1.82138771e-01, -2.75230734e-03, -2.29673870e-02,  6.47304282e-02,
        -2.07118005e-01, -1.04713984e-01, -1.19404875e-01, -1.09362751e-01,
        -5.86776398e-02,  1.98414549e-02,  1.93376057e-02, -2.56121159e-04,
        -1.33486509e-01, -1.98222682e-01, -1.38347447e-01, -1.39369115e-01,
         1.74305543e-01, -8.88103619e-02,  8.94454867e-03,  7.46188834e-02,
        -1.58124194e-01, -8.83737504e-02,  5.53894117e-02,  1.27452284e-01,
        -7.51968324e-02, -2.25475021e-02,  1.85055569e-01,  2.11284533e-02,
        -1.41231060e-01, -2.23658308e-02,  6.15880527e-02,  2.53549188e-01,
         2.68987596e-01,  8.67981687e-02,  5.98824956e-03, -4.37789746e-02,
         1.42188653e-01, -2.27694154e-01,  7.68692195e-02,  1.65807411e-01,
         2.0

In [90]:
list1 = knownEncodings.tolist()

AttributeError: 'list' object has no attribute 'tolist'

In [91]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [92]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(f'NumPy Array:\n{arr}')

list1 = arr.tolist()

print(f'List: {list1}')

NumPy Array:
[[1 2 3]
 [4 5 6]]
List: [[1, 2, 3], [4, 5, 6]]


In [94]:
type(arr)

numpy.ndarray

In [95]:
type(knownEncodings)

list

In [96]:
len(knownEncodings)

15

In [104]:
knownEncodings[0]

array([-7.78014883e-02,  1.00938603e-01,  1.27612893e-02, -1.54165216e-02,
       -1.74832687e-01, -2.33827960e-02, -7.97428042e-02, -1.49676085e-01,
        1.29436016e-01, -7.45923519e-02,  1.47503763e-01,  7.45223835e-03,
       -1.82138771e-01, -2.75230734e-03, -2.29673870e-02,  6.47304282e-02,
       -2.07118005e-01, -1.04713984e-01, -1.19404875e-01, -1.09362751e-01,
       -5.86776398e-02,  1.98414549e-02,  1.93376057e-02, -2.56121159e-04,
       -1.33486509e-01, -1.98222682e-01, -1.38347447e-01, -1.39369115e-01,
        1.74305543e-01, -8.88103619e-02,  8.94454867e-03,  7.46188834e-02,
       -1.58124194e-01, -8.83737504e-02,  5.53894117e-02,  1.27452284e-01,
       -7.51968324e-02, -2.25475021e-02,  1.85055569e-01,  2.11284533e-02,
       -1.41231060e-01, -2.23658308e-02,  6.15880527e-02,  2.53549188e-01,
        2.68987596e-01,  8.67981687e-02,  5.98824956e-03, -4.37789746e-02,
        1.42188653e-01, -2.27694154e-01,  7.68692195e-02,  1.65807411e-01,
        2.06845015e-01,  

In [117]:
list(dict.fromkeys(knownEncodings))

TypeError: unhashable type: 'list'

In [120]:
set(map(tuple, knownEncodings))

TypeError: unhashable type: 'numpy.ndarray'

In [121]:
animal_groups = [['fox','monkey', 'zebra'], ['snake','elephant', 'donkey'],['beetle', 'mole', 'mouse'],['fox','monkey', 'zebra']]
animal_groups

[['fox', 'monkey', 'zebra'],
 ['snake', 'elephant', 'donkey'],
 ['beetle', 'mole', 'mouse'],
 ['fox', 'monkey', 'zebra']]

In [122]:
set(map(tuple, animal_groups))

{('beetle', 'mole', 'mouse'),
 ('fox', 'monkey', 'zebra'),
 ('snake', 'elephant', 'donkey')}

In [123]:
knownEncodings2 = list(knownEncodings)

In [124]:
type(knownEncodings2)

list

In [125]:
knownEncodings2

[[array([-7.78014883e-02,  1.00938603e-01,  1.27612893e-02, -1.54165216e-02,
         -1.74832687e-01, -2.33827960e-02, -7.97428042e-02, -1.49676085e-01,
          1.29436016e-01, -7.45923519e-02,  1.47503763e-01,  7.45223835e-03,
         -1.82138771e-01, -2.75230734e-03, -2.29673870e-02,  6.47304282e-02,
         -2.07118005e-01, -1.04713984e-01, -1.19404875e-01, -1.09362751e-01,
         -5.86776398e-02,  1.98414549e-02,  1.93376057e-02, -2.56121159e-04,
         -1.33486509e-01, -1.98222682e-01, -1.38347447e-01, -1.39369115e-01,
          1.74305543e-01, -8.88103619e-02,  8.94454867e-03,  7.46188834e-02,
         -1.58124194e-01, -8.83737504e-02,  5.53894117e-02,  1.27452284e-01,
         -7.51968324e-02, -2.25475021e-02,  1.85055569e-01,  2.11284533e-02,
         -1.41231060e-01, -2.23658308e-02,  6.15880527e-02,  2.53549188e-01,
          2.68987596e-01,  8.67981687e-02,  5.98824956e-03, -4.37789746e-02,
          1.42188653e-01, -2.27694154e-01,  7.68692195e-02,  1.65807411e-01,

In [127]:
knownEncodings

[[array([-7.78014883e-02,  1.00938603e-01,  1.27612893e-02, -1.54165216e-02,
         -1.74832687e-01, -2.33827960e-02, -7.97428042e-02, -1.49676085e-01,
          1.29436016e-01, -7.45923519e-02,  1.47503763e-01,  7.45223835e-03,
         -1.82138771e-01, -2.75230734e-03, -2.29673870e-02,  6.47304282e-02,
         -2.07118005e-01, -1.04713984e-01, -1.19404875e-01, -1.09362751e-01,
         -5.86776398e-02,  1.98414549e-02,  1.93376057e-02, -2.56121159e-04,
         -1.33486509e-01, -1.98222682e-01, -1.38347447e-01, -1.39369115e-01,
          1.74305543e-01, -8.88103619e-02,  8.94454867e-03,  7.46188834e-02,
         -1.58124194e-01, -8.83737504e-02,  5.53894117e-02,  1.27452284e-01,
         -7.51968324e-02, -2.25475021e-02,  1.85055569e-01,  2.11284533e-02,
         -1.41231060e-01, -2.23658308e-02,  6.15880527e-02,  2.53549188e-01,
          2.68987596e-01,  8.67981687e-02,  5.98824956e-03, -4.37789746e-02,
          1.42188653e-01, -2.27694154e-01,  7.68692195e-02,  1.65807411e-01,

In [128]:
[list(t) for t in set(map(tuple, animal_groups))]

[['snake', 'elephant', 'donkey'],
 ['beetle', 'mole', 'mouse'],
 ['fox', 'monkey', 'zebra']]

In [131]:
np.unique(knownEncodings, axis=0)

array([[[-1.12896584e-01,  8.76956061e-02,  7.52159581e-02,
         -2.40226388e-02, -1.82425141e-01, -2.32556351e-02,
         -8.84586945e-02, -1.39373094e-01,  1.27347276e-01,
         -9.01777744e-02,  1.76046714e-01,  3.89306881e-02,
         -2.16497347e-01, -3.99931371e-02, -2.24681757e-02,
          8.85967389e-02, -1.83221698e-01, -1.12569191e-01,
         -1.50113791e-01, -1.00487225e-01, -2.77942177e-02,
         -9.48068313e-03,  4.76543754e-02, -1.89771745e-02,
         -1.37209713e-01, -2.17317849e-01, -1.51669532e-01,
         -1.19017288e-01,  1.70201033e-01, -7.24604949e-02,
          2.15993896e-02,  5.04418164e-02, -1.62162051e-01,
         -1.07638940e-01,  3.61398980e-02,  1.59104764e-01,
         -3.63050736e-02, -2.83724181e-02,  2.14211255e-01,
         -3.54451723e-02, -1.53919518e-01,  2.04607518e-03,
          6.81841671e-02,  2.29787946e-01,  2.42911890e-01,
          6.51404038e-02,  3.70198265e-02, -4.79621291e-02,
          1.25815123e-01, -2.74076402e-0

In [137]:
knownEncodings2 = list(dict.fromkeys(list(np.unique(knownEncodings2, axis=0)))

SyntaxError: unexpected EOF while parsing (<ipython-input-137-7271e02b49e6>, line 1)

In [133]:
type(np.unique(knownEncodings, axis=0))

numpy.ndarray

In [138]:
knownEncodings2 = list(np.unique(knownEncodings, axis=0))

In [139]:
knownEncodings2

[array([[-0.11289658,  0.08769561,  0.07521596, -0.02402264, -0.18242514,
         -0.02325564, -0.08845869, -0.13937309,  0.12734728, -0.09017777,
          0.17604671,  0.03893069, -0.21649735, -0.03999314, -0.02246818,
          0.08859674, -0.1832217 , -0.11256919, -0.15011379, -0.10048722,
         -0.02779422, -0.00948068,  0.04765438, -0.01897717, -0.13720971,
         -0.21731785, -0.15166953, -0.11901729,  0.17020103, -0.07246049,
          0.02159939,  0.05044182, -0.16216205, -0.10763894,  0.0361399 ,
          0.15910476, -0.03630507, -0.02837242,  0.21421126, -0.03544517,
         -0.15391952,  0.00204608,  0.06818417,  0.22978795,  0.24291189,
          0.0651404 ,  0.03701983, -0.04796213,  0.12581512, -0.2740764 ,
          0.06569149,  0.16664654,  0.17026408,  0.08951093,  0.13467029,
         -0.19395824,  0.10647263,  0.20650184, -0.13748106,  0.11858997,
          0.11436874, -0.16743772,  0.00487409,  0.01872457,  0.18902627,
          0.08523169, -0.03599659, -0.

In [140]:
knownEncodings2 = list(dict.fromkeys(knownEncodings2))

TypeError: unhashable type: 'numpy.ndarray'