In [1]:
from keras.datasets import mnist
#download mnist data and split into train and test sets
(X_train, y_train), (X_test, y_test) = mnist.load_data()

Using TensorFlow backend.


In [2]:
import matplotlib.pyplot as plt
#plot the first image in the dataset
plt.imshow(X_train[0])

In [3]:
#check image shape
X_train[0].shape

(28, 28)

In [4]:
#reshape data to fit model
X_train = X_train.reshape(60000,28,28,1)
X_test = X_test.reshape(10000,28,28,1)

In [5]:
from keras.utils import to_categorical
#one-hot encode target column
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)
y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [7]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten
#create model
model = Sequential()
#add model layers
model.add(Conv2D(64, kernel_size=3, activation='relu', input_shape=(28,28,1)))
model.add(Conv2D(32, kernel_size=3, activation='relu'))
model.add(Flatten())
model.add(Dense(10, activation='softmax'))

Instructions for updating:
Colocations handled automatically by placer.


In [8]:
#compile model using accuracy to measure model performance
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [9]:
#train the model
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=3)

Instructions for updating:
Use tf.cast instead.
Train on 60000 samples, validate on 10000 samples
Epoch 1/3
60000/60000 [==============================] - 223s 4ms/step - loss: 0.4007 - acc: 0.9403 - val_loss: 0.0856 - val_acc: 0.9731
Epoch 2/3
60000/60000 [==============================] - 173s 3ms/step - loss: 0.0653 - acc: 0.9801 - val_loss: 0.0762 - val_acc: 0.9784
Epoch 3/3
60000/60000 [==============================] - 171s 3ms/step - loss: 0.0423 - acc: 0.9870 - val_loss: 0.1037 - val_acc: 0.9731


In [10]:
#predict first 4 images in the test set
model.predict(X_test[:4])

array([[2.4438716e-08, 1.4686613e-13, 3.4251787e-08, 2.6219906e-05,
        1.0605119e-13, 3.9106565e-11, 1.8732422e-15, 9.9997377e-01,
        1.7152652e-09, 9.7440864e-09],
       [1.5428536e-07, 2.2498398e-08, 9.9999964e-01, 5.5934195e-09,
        2.8712234e-12, 5.0836197e-12, 2.3462971e-07, 3.4612795e-14,
        1.1665244e-09, 1.3353988e-15],
       [6.1217783e-05, 9.6973789e-01, 1.5432101e-03, 1.1710987e-06,
        1.0924516e-02, 1.7986842e-05, 1.7692444e-04, 9.2599721e-06,
        1.7506011e-02, 2.1860829e-05],
       [1.0000000e+00, 1.7096983e-13, 7.2729538e-09, 3.3779323e-12,
        6.8052586e-12, 5.5022387e-10, 3.4914539e-08, 3.9492480e-12,
        5.2995619e-10, 1.3888124e-08]], dtype=float32)

In [11]:
#actual results for first 4 images in test set
y_test[:4]

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)