In [7]:
import numpy as np

In [9]:
A = np.array([3,5,7])
A

array([3, 5, 7])

In [11]:
A.shape

(3,)

In [12]:
A.dtype

dtype('int32')

In [14]:
B = np.array([[8.2, 7.5, 6], [4, 3.5, 3]])
B

array([[8.2, 7.5, 6. ],
       [4. , 3.5, 3. ]])

In [15]:
B.shape

(2, 3)

In [16]:
B.dtype

dtype('float64')

In [17]:
A

array([3, 5, 7])

In [18]:
C = np.array([[2, 4], [5, 8], [7, 2]])
C

array([[2, 4],
       [5, 8],
       [7, 2]])

In [20]:
print("elemen matriks baris 3 kolom 2: ")
C[2, 1]

elemen matriks baris 3 kolom 2: 


2

In [21]:
D = np.array([[1, 3], [2, 4], [5, 2]])
D

array([[1, 3],
       [2, 4],
       [5, 2]])

In [23]:
C

array([[2, 4],
       [5, 8],
       [7, 2]])

In [24]:
#penjumlahan matriks
C + D

array([[ 3,  7],
       [ 7, 12],
       [12,  4]])

In [25]:
C + 10

array([[12, 14],
       [15, 18],
       [17, 12]])

In [26]:
C - D

array([[1, 1],
       [3, 4],
       [2, 0]])

In [28]:
D - C

array([[-1, -1],
       [-3, -4],
       [-2,  0]])

In [29]:
C * 10

array([[20, 40],
       [50, 80],
       [70, 20]])

In [30]:
A

array([3, 5, 7])

In [31]:
A * C

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [38]:
C * D

array([[ 2, 12],
       [10, 32],
       [35,  4]])

In [39]:
C

array([[2, 4],
       [5, 8],
       [7, 2]])

In [40]:
D

array([[1, 3],
       [2, 4],
       [5, 2]])

In [41]:
C/2

array([[1. , 2. ],
       [2.5, 4. ],
       [3.5, 1. ]])

In [42]:
C/D

array([[2.        , 1.33333333],
       [2.5       , 2.        ],
       [1.4       , 1.        ]])

In [45]:
print(C)
np.sum(C)

[[2 4]
 [5 8]
 [7 2]]


28

In [46]:
np.sum(C, axis=0)

array([14, 14])

In [47]:
np.sum(C, axis=1)

array([ 6, 13,  9])

In [49]:
C.T

array([[2, 5, 7],
       [4, 8, 2]])

In [50]:
C

array([[2, 4],
       [5, 8],
       [7, 2]])

In [52]:
nilai = np.array([7, 6, 8, 9, 5])
print("nilai: ", np.mean(nilai))

nilai:  7.0


In [53]:
print("nilai: ", np.median(nilai))

nilai:  7.0


In [57]:
nilai1 = np.array([7, 6, 8, 9, 5, 7, 6, 7, 4, 3])
print(np.mean(nilai1))
print(np.std(nilai1)) #standar deviasi

6.2
1.7204650534085253


In [58]:
np.min(nilai1)

3

In [59]:
np.max(nilai1)

9